config/routes.rb
Rails.application.routes.draw do
  # Homepage
  root 'home#index'

  # Signup path
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # Authentication path
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  # Contacts
  resources :contacts, except: [:show] do
    collection do
      get 'archived'
      get 'search'
    end

    member do
      patch 'restore'
      get 'download-vcard'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  default_scope { where(deleted_at: nil) }
  scope :archived, -> { where.not(deleted_at: nil) }

  belongs_to :user

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, length: { maximum: 20 }
  validates :address, length: { maximum: 255 }
  validates :organization, length: { maximum: 100 }
  VALID_DATE_REGEX = /(\d){4}-\d{2}-\d{2}/
  validates :birthday, length: { maximum: 10 }, format: { with: VALID_DATE_REGEX }, allow_nil: true

  # Email Validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
    format: { with: VALID_EMAIL_REGEX }, uniqueness: { 
      case_sensitive: false, scope: [:user_id, :email] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contacts

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 }, 
    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 }

  has_secure_password

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    # Confirms that user is logged in
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please login first."
        redirect_to login_url                                                                                                                        
      end
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:destroy, :restore, :download_vcard]

  def index
    @contacts = current_user.contacts.sort_by { |contact| contact.name.downcase }
  end

  def new
    @contact = current_user.contacts.build
  end

  def create
    @contact = current_user.contacts.build(contact_params)
    if @contact.save
      flash[:success] = "Contact added."
      redirect_to contacts_url
    else
      render 'new'
    end
  end

  def destroy
    @contact.update_attribute(:deleted_at, DateTime.now)
    flash[:success] = "Contact <#{@contact.name}> archived."
    redirect_to contacts_url
  end

  def archived
    @archived_contacts = Contact.unscoped.archived.where(user: current_user)
  end

  def restore 
    @contact.update_attribute(:deleted_at, nil)
    flash[:success] = "Contact <#{@contact.name}> restored."
    redirect_to archived_contacts_url
  end

  def download_vcard
    respond_to do |format|
      format .vcf do
        send_data generate_vcard(@contact).to_s, :filename => "#{@contact.name.parameterize}.vcf", :type => :vcf
      end
    end
  end

  def search
    @keyword = params[:keyword]
    unless @keyword.blank?
      @matched_contacts = Contact.unscoped
        .where(user: current_user)
        .where("name LIKE :keyword OR email LIKE :keyword OR organization LIKE :keyword OR address LIKE :keyword", keyword: "%#{@keyword}%")
    end
  end

  private

    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :address, :organization, :birthday)
    end

    # Confirms that the contact belongs to current user
    def correct_user
      @contact = Contact.unscoped.find(params[:id])
      redirect_to root_url unless current_user?(@contact.user)
    end

    # Generate VCard from contact
    def generate_vcard(contact)
      vcard = VCardigan.create
      vcard.fullname contact.name
      vcard.email contact.email
      vcard.tel contact.phone
      vcard.address contact.address
      vcard.org contact.organization
      vcard.birthday contact.birthday

      return vcard
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]
  before_action :correct_user, only: [:show]

  def show
    @contacts_count = @user.contacts.count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Sign up successful! Welcome to Contacts App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Confirms that the user is correct
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Contacts App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Login the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns true if the given user is current user
  def current_user?(user)
    user == current_user
  end

  # Returns the currently logged in user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Check whether the user is logged in
  def logged_in?
    !current_user.nil?
  end

  # Log out current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_contact.html.erb
        <a class="list-group-item" data-toggle="collapse" href="#details-<%= contact_counter %>">
          <h4>
            <%= contact.name %> <small>&lt;<%= contact.email %>&gt;</small>
          </h4>
        </a>
        <div class="collapse" id="details-<%= contact_counter %>">
          <div class="well">
            <% unless contact.phone.blank? %>
              <p><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> <%= contact.phone %></p>
            <% end %>
            <% unless contact.address.blank? %>
              <p><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> <%= contact.address %></p>
            <% end %>
            <% unless contact.organization.blank? %>
              <p><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> <%= contact.organization %></p>
            <% end %>
            <% unless contact.birthday.blank? %>
              <p><span class="glyphicon glyphicon-gift" aria-hidden="true"></span> Born <%= contact.birthday.to_s(:long) %></p>
            <% end %>
            <p><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Added <%= time_ago_in_words contact.created_at %> ago</p>

            <% unless contact.deleted_at %>
              <%= link_to fa_icon("archive") + " Archive", contact, class: "btn btn-sm btn-warning", 
                method: :delete, data: { confirm: "Are you sure to archive #{contact.name}?" } %>
            <% else %>
              <%= link_to fa_icon("undo") + " Restore".html_safe, restore_contact_path(contact),
                class: "btn btn-sm btn-success", method: :patch %> 
            <% end %>

            <%= link_to( fa_icon("download") + " VCard".html_safe,  download_vcard_contact_path(contact.id, :format => 'vcf'), class: "btn btn-sm btn-info")  %>
          </div>
        </div>

app/views/contacts/archived.html.erb
<% provide(:title, "Archived Contacts")%>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <h1 class="text-center">Archived Contacts</h1>

    <ul class="list-group">
      <% if @archived_contacts.present? %>
        <%= render partial: "contact", collection: @archived_contacts, as: :contact %>
      <% else %>
        <%= "No archived contacts." %>
      <% end %>
    </ul>

  </div>
</div>

app/views/contacts/index.html.erb
<% provide(:title, "My Contacts")%>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <h1 class="text-center">My Contacts</h1>

    <%= link_to " + Add Contact", new_contact_path, class: "btn btn-default" %>

    <ul class="list-group">
      <%= render(@contacts) || "No contact added." %>
    </ul>

  </div>
</div>

app/views/contacts/new.html.erb
<% provide(:title, "Add Contact") %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <h1 class="text-center">New Contact</h1>

    <%= form_for @contact, html: { class: "form-horizontal" } do |f| %>
      <%= render 'shared/error_messages', object: @contact %>

      <div class="form-group">
        <%= f.label :name, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :email, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :phone, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.telephone_field :phone, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :address, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :address, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :organization, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :organization, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :birthday, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.date_field :birthday, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
          <%= f.submit "Add", class: "btn btn-primary" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/contacts/search.html.erb
<% provide(:title, "Search Contact")%>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <h1 class="text-center">Search result of "<%= @keyword %>"</h1>
    <h4 class="text-center"><%= pluralize @matched_contacts.count, "result" if @matched_contacts.present? %></h4>

    <ul class="list-group">
      <% if @matched_contacts.present? %>
        <%= render partial: "contact", collection: @matched_contacts, as: :contact %>
      <% else %>
        <%= "No matched contacts." %>
      <% end %>
    </ul>

  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <% if logged_in? %>
    <h1>Contacts App</h1>
    <p><%= link_to "My Contacts", contacts_path, class: "btn btn-primary btn-lg" %></p>
  <% else %>
    <h1>Welcome to Contacts App</h1>
    <p><%= link_to "Sign Up", signup_path, class: "btn btn-primary btn-lg" %></p>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ContactsApp</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->                                                                            
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if logged_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to fa_icon("address-book") + " My Contacts", contacts_path %></li>
          <li><%= link_to fa_icon("archive") + " Archived Contacts", archived_contacts_path %></li>
        </ul>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Welcome, #{current_user.name}", "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= fa_icon "user" %></span> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>

      <% if logged_in? %>
        <form class="navbar-form navbar-right" action="<%= search_contacts_path %>" method="get">
          <div class="form-group">
            <input type="text" name="keyword" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-primary"><%= fa_icon("search") %></button>
        </form>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some <%= pluralize(object.errors.count, "error") %> with your input.<br><br>
        <ul>
            <% object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
            <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <h1 class="text-center">Sign up</h1>

    <%= form_for @user, url: signup_path, html: { class: "form-horizontal" } do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <div class="form-group">
        <%= f.label :name, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :email, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation", class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
          <%= f.submit "Create my account", class: "btn btn-primary" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1><%= @user.name %></h1>

<p class="lead"><%= pluralize @contacts_count, "contact" %></p>